# Generated by Django 3.2.8 on 2022-06-10 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_url', models.URLField(default='https://kun.uz', null=True, unique=True)),
                ('news_name', models.CharField(default='News name', max_length=25, null=True)),
                ('news_count_views', models.IntegerField(default=1, null=True)),
                ('news_text', models.TextField(default='0', null=True)),
                ('news_date', models.DateTimeField(null=True)),
            ],
        ),
    ]
